// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace VicGovResiEnvelope
{
    public class VicGovResiEnvelopeOutputs: ResultsBase
    {
		/// <summary>
		/// The required side and rear setback from boundary derived from the proposed building height
		/// </summary>
		[JsonProperty("Side and rear setback")]
		public double SideAndRearSetback {get;}

		/// <summary>
		/// The front setback defined by the allotment type and front face condition
		/// </summary>
		[JsonProperty("Front setback")]
		public double FrontSetback {get;}



        /// <summary>
        /// Construct a VicGovResiEnvelopeOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public VicGovResiEnvelopeOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a VicGovResiEnvelopeOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public VicGovResiEnvelopeOutputs(double sideAndRearSetback, double frontSetback): base()
        {
			this.SideAndRearSetback = sideAndRearSetback;
			this.FrontSetback = frontSetback;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}